resources:
  - ../base/storage
  - ../base/tigera-operator
  - ../base/calico-system
  - ../base/vault-secrets-operator
  - ../base/vault
patches:
  - target:
      kind: Installation
      name: default
      namespace: calico-system
    patch: |-
      - op: replace
        path: /spec/calicoNetwork/ipPools/0/cidr
        value: "192.169.0.0/16"

  - target:
      kind: Ingress
      name: vault
      namespace: vault
    patch: |-
      - op: replace
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: infra-vault.vinlab.org

      - op: replace
        path: /spec/rules/0/host
        value: infra-vault.vinlab.org

      - op: replace
        path: /spec/tls/0/hosts/0
        value: infra-vault.vinlab.org
